#!/bin/sh -e

serviceName=debian-package-demo

adduser --system debian-package-demo --home /usr/lib/debian-package-demo

systemctl daemon-reload
if ! systemctl is-active --quiet ${serviceName}; then
	echo "Starting ${serviceName}..."
	systemctl start ${serviceName}
fi

exit 0

