#!/bin/sh -e

userName=debian-package-demo
serviceName=debian-package-demo

if ! id ${userName} > /dev/null 2>&1; then
	adduser --quiet --system ${userName} --home /usr/lib/${serviceName}
	# Because the Java application will schedule one-off systemd user
	# services systemd session has to exist for user even if the user
	# is not logged-in. To ensure this session lingering will be enabled
	# for user.
	loginctl enable-linger ${userName}
fi

systemctl daemon-reload
if ! systemctl is-active --quiet ${serviceName}; then
	echo "Starting ${serviceName} service..."
	systemctl enable ${serviceName}
	systemctl start ${serviceName}
fi

exit 0

